name: podcasts
base: core24 
adopt-info: podcasts
grade: stable
confinement: strict 
license: GPL-3.0-only
website: https://github.com/soumyaDghosh/podcasts-snap
source-code: https://gitlab.gnome.org/World/podcasts
issues: https://github.com/soumyaDghosh/podcasts-snap/issues

platforms:
  amd64:
  arm64:

parts:
  rustup:
    plugin: rust
    source: .
    rust-channel: "1.80"
    override-build: ""
    override-prime: ""

  podcasts:
    after: [ rustup ]
    plugin: meson
    source: https://gitlab.gnome.org/World/podcasts.git
    source-tag: '25.3'
    source-depth: 1
    meson-parameters:
      - --prefix=/snap/podcasts/current/usr
      - -Dprofile=default
    build-environment:
      - PATH: ${HOME}/.cargo/bin:${PATH}
    override-pull: |
      craftctl default
      sed -i '0,/APP_ID.to_string()/{s/APP_ID.to_string()/"Podcasts".to_string()/}' $CRAFT_PART_SRC/podcasts-gtk/src/widgets/player.rs
    build-packages:
      - libssl-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev 
    parse-info: [ usr/share/metainfo/org.gnome.Podcasts.appdata.xml ]
    organize: 
      snap/podcasts/current: .


slots:
  podcasts:
    interface: dbus
    bus: session
    name: org.gnome.Podcasts
  mpris:
    interface: mpris
    name: Podcasts
apps:
  podcasts:
    command: usr/bin/gnome-podcasts
    desktop: usr/share/applications/org.gnome.Podcasts.desktop
    common-id: org.gnome.Podcasts
    extensions: [ gnome ]
    plugs:
      - network
      - network-bind
      - network-status
      - audio-playback
      - screen-inhibit-control
