name: podcasts # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: podcasts
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: ''
  podcasts:
    after: [ rustup ]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.gnome.org/World/podcasts.git
    source-tag: '0.5.1'
    meson-parameters:
      - --prefix=/snap/podcasts/current/usr
      - -Dprofile=default
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    build-packages:
      - libssl-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/podcasts.patch
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/podcasts/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    parse-info: [ usr/share/metainfo/org.gnome.Podcasts.appdata.xml ]


slots:
  podcasts:
    interface: dbus
    bus: session
    name: org.gnome.Podcasts
apps:
  podcasts:
    command: usr/bin/gnome-podcasts
    desktop: usr/share/applications/org.gnome.Podcasts.desktop
    common-id: org.gnome.Podcasts
    extensions: [ gnome ]
    plugs:
      - network
      - network-bind
      - network-status
      - audio-playback
