name: podcasts
base: core22 
adopt-info: podcasts
grade: stable
confinement: strict 

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: ''
  podcasts:
    after: [ rustup ]
    plugin: meson
    source: https://gitlab.gnome.org/World/podcasts.git
    source-tag: '0.6.1'
    meson-parameters:
      - --prefix=/snap/podcasts/current/usr
      - -Dprofile=default
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    build-packages:
      - libssl-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev 
    parse-info: [ usr/share/metainfo/org.gnome.Podcasts.appdata.xml ]


slots:
  podcasts:
    interface: dbus
    bus: session
    name: org.gnome.Podcasts
apps:
  podcasts:
    command: usr/bin/gnome-podcasts
    desktop: usr/share/applications/org.gnome.Podcasts.desktop
    common-id: org.gnome.Podcasts
    extensions: [ gnome ]
    plugs:
      - network
      - network-bind
      - network-status
      - audio-playback
